### ISSUE TITLE
no effect when pressing "set"

### ISSUE THREAD

**Issue by BenFradella** [MohamadSaada/LogiGSK#29]
I have a logitech g910 keyboard. I'm running ubuntu 18.04 with kde-plasma and I got the software to install without issue. The keyboard shows up in the GUI but when I press the 'set' button nothing happens. Still stuck on the default rainbow wave effect.

**Comment by crimv42** [comment]
I am also on Ubuntu 18.04 and having the same results.

**Comment by MohamadSaada** [comment]
@BenFradella @crimv42, I will test it today on Ubuntu 18.04 and confirm if there is a problem. I will let you know once tested.

**Comment by darksaboteur** [comment]
I am on Fedora 29 Beta and am encountering the same issue. My keys are stuck on the default blue colour.

**Comment by zkarj** [comment]
I can confirm on Fedora 27 x86_64 too with Logitech G910 Orion Spectrum. I downloaded the binary rpm.

I installed rpmrebuild and apache-commons-daemon-jsvc and run rpmrebuild -ep to modify the rpm file and remove /, /usr, /usr/bin, then comment out all debconf script run entries since they don't exist.

I ran LogiGSK.sh fine and even chmod 666 /dev/usb/hiddev* (I didn't setup udev rules yet), but no go. Do we require the daemon even for Set?

The error message is 
```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/var/tmp
Oct 20, 2018 6:51:49 PM Logi.GSeries.Service.LogiGSKService$Manager <init>
INFO: New connection with client# 0 at Socket[addr=/127.0.0.1,port=35864,localpo
rt=9898]
Oct 20, 2018 6:51:49 PM Logi.GSeries.Service.LogiGSKService$Manager run
INFO: Response: yj7UYIbTdy1JhIH9f1lK/fGXItxcwXuxEnsWFcLuLfE=
Oct 20, 2018 6:51:49 PM Logi.GSeries.Service.LogiGSKService$Manager run
INFO: Connection with client# 0 closed
Oct 20, 2018 6:51:49 PM Logi.GSeries.Keyboard.CommunicationClient sendCommand
INFO: Connection with Logi G Keyboard service closed.
```

**Comment by zkarj** [comment]
Ok, I finally made it work. It was the LogiGSK.rules that had to be inside /etc/udev/rules.d/ so that the permission is correctly set for access by normal users.

I also compiled the latest git version, then use rpmrebuild -ep to replace the jar file in the rpm package (on top of the spec file that had be edited as mentioned above), and that may have helped.

I think logigsk-buildpackage needs to be fixed to make it correctly setup the install scripts and generate rpm without relying on deb or alien.

**Comment by darksaboteur** [comment]
@zkarj That is great news. Could you please provide the rpm file you built? I can not get mine to work following your instructions

**Comment by Flare183** [comment]
Still happening here. When I fire up LogiGSK, it just spits out 
`└─[130] <> logigsk
Connected: 046d:c32b
Apr 15, 2019 2:51:11 AM Logi.GSeries.Keyboard.LogiGSK pauseServiceOperations
SEVERE: null
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at Logi.GSeries.Keyboard.CommunicationClient.sendCommand(CommunicationClient.java:56)
	at Logi.GSeries.Keyboard.LogiGSK.pauseServiceOperations(LogiGSK.java:1187)
	at Logi.GSeries.Keyboard.LogiGSK.access$000(LogiGSK.java:44)
	at Logi.GSeries.Keyboard.LogiGSK$Callback.processEvent(LogiGSK.java:173)
	at org.usb4java.LibUsb.hotplugCallback(LibUsb.java:2778)
	at org.usb4java.LibUsb.hotplugRegisterCallbackNative(Native Method)
	at org.usb4java.LibUsb.hotplugRegisterCallback(LibUsb.java:2841)
	at Logi.GSeries.Keyboard.LogiGSK.main(LogiGSK.java:1083)

Speed not: 12
Slider position: 5
Speed: 50`

Pressing set does nothing :( It used to work idk what's wrong with it now

**Comment by wraith3690** [comment]
mint 19.3 hitting set does nothing for me it was working before but not now @zkarj can you share more clearly what it is that you did to fix it

**Comment by ghost** [comment]
I'm on fedora 33. I installed logisk with the install script. When I try to run `logisk start`, it crashes my desktop session and forces me to log out. Setting does nothing either, and I suspect this is because the service isn't actually running.

**Comment by ghost** [comment]
Though it says it is already setup to startup automatically :shrug:

**Comment by ghost** [comment]
> Still happening here. When I fire up LogiGSK, it just spits out
> `└─[130] <> logigsk
> Connected: 046d:c32b
> Apr 15, 2019 2:51:11 AM Logi.GSeries.Keyboard.LogiGSK pauseServiceOperations
> SEVERE: null
> java.net.ConnectException: Connection refused (Connection refused)
> at java.net.PlainSocketImpl.socketConnect(Native Method)
> at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> at java.net.Socket.connect(Socket.java:589)
> at java.net.Socket.connect(Socket.java:538)
> at java.net.Socket.(Socket.java:434)
> at java.net.Socket.(Socket.java:244)
> at Logi.GSeries.Keyboard.CommunicationClient.sendCommand(CommunicationClient.java:56)
> at Logi.GSeries.Keyboard.LogiGSK.pauseServiceOperations(LogiGSK.java:1187)
> at Logi.GSeries.Keyboard.LogiGSK.access$000(LogiGSK.java:44)
> at Logi.GSeries.Keyboard.LogiGSK$Callback.processEvent(LogiGSK.java:173)
> at org.usb4java.LibUsb.hotplugCallback(LibUsb.java:2778)
> at org.usb4java.LibUsb.hotplugRegisterCallbackNative(Native Method)
> at org.usb4java.LibUsb.hotplugRegisterCallback(LibUsb.java:2841)
> at Logi.GSeries.Keyboard.LogiGSK.main(LogiGSK.java:1083)
> 
> Speed not: 12
> Slider position: 5
> Speed: 50`
> 
> Pressing set does nothing :( It used to work idk what's wrong with it now

I get the same thing when I try to launch it from the terminal, I just launch in from the desktop entry anyways, but I guess I can't really do much debugging with it like this.

**Comment by ghost** [comment]
Though when I used the jar provided in releases, I got this instead:
```sh
❯ java -jar LogiGSK.jar
Error: Unable to initialize main class Logi.GSeries.Keyboard.LogiGSK
Caused by: java.lang.NoClassDefFoundError: org/usb4java/LibUsbException
```

**Comment by pebkacs** [comment]
I am on Ubuntu 22.04, installed from the prepackaged deb file.  I was not getting any changes when I clicked `set`, but I had `g910-gkeys` installed and running as well.  After stopping `g910-gkeys` and restarting `logigsk-service`, everything is happy.  I figure there might be a number of us that have installed both.

**Comment by wraith3690** [comment]
@pebkacs thats great that you got it working but it seems this project is dead (I could be wrong) and it does not give you gkey support I have sense moved to openrgb it works with many different devices including the g910 and for setting the G and M keys I use keyboard center (which works with openrgb) with those 2 programs I get 100% functionality of the g910 here are the links to the projects 

https://github.com/zocker-160/keyboard-center
https://openrgb.org/

**Comment by pebkacs** [comment]
Hi @wraith3690,

Yeah, I know the project is dead, but I figured there might still be someone out there trying to use it too.

I just installed OpenRGB last night.  I always thought that was just for motherboard controllers, so I never thought about trying it until just after I posted last night.  The only problem is that right now I can't seem to get i2c working with it, so it can't see my RGB devices.

**Comment by wraith3690** [comment]
this page may help you https://gitlab.com/CalcProgrammer1/OpenRGB it has some info on that and if you installed by Flatpak or are using an Appimage you will need to install the udev rules yourself

**Comment by pebkacs** [comment]
Thanks a bunch.  I'll give it a look.
